# Generated by Django 5.1.4 on 2024-12-14 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetables_prices', '0002_careguide_plantingguide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegetableprice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vegetableprice',
            name='price',
        ),
        migrations.CreateModel(
            name='VegetableSeedCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seeds_per_plant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yield_per_plant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plant_spacing_cm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('row_spacing_cm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vegetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vegetables_prices.vegetable')),
            ],
        ),
    ]
